apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cleanenergy
    app.kubernetes.io/instance: cleanenergy-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managen-by: kubectl
  name: cleanenergy
spec:
  selector:
    app: cleanenergy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80